#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-objenesis
Version  : 2.6
Release  : 2
URL      : https://repo1.maven.org/maven2/org/objenesis/objenesis/2.6/objenesis-2.6.jar
Source0  : https://repo1.maven.org/maven2/org/objenesis/objenesis/2.6/objenesis-2.6.jar
Source1  : https://repo1.maven.org/maven2/org/objenesis/objenesis-parent/2.6/objenesis-parent-2.6.pom
Source2  : https://repo1.maven.org/maven2/org/objenesis/objenesis/2.6/objenesis-2.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-objenesis-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-objenesis package.
Group: Data

%description data
data components for the mvn-objenesis package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis-parent/2.6
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis-parent/2.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/objenesis/objenesis-parent/2.6/objenesis-parent-2.6.pom
/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar
/usr/share/java/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.pom
